services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: timeforing
      POSTGRES_USER: timeforing_user
      POSTGRES_PASSWORD: timeforing_pass
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U timeforing_user -d timeforing" ]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
        db:
          condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/timeforing
      SPRING_DATASOURCE_USERNAME: timeforing_user
      SPRING_DATASOURCE_PASSWORD: timeforing_pass

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "5"
      SPRING_PROFILES_ACTIVE: dev

      APP_JWT_ISSUER: mock-auth
      APP_JWT_AUDIENCE: timesheet-app
      APP_JWT_SECRET: ${APP_JWT_SECRET}
      APP_AUTH_ADMIN_EMAILS: admin@example.com
