services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "5"

      APP_JWT_ISSUER: mock-auth
      APP_JWT_AUDIENCE: timesheet-app
      APP_JWT_SECRET: ${APP_JWT_SECRET}
      APP_AUTH_ADMIN_EMAILS: admin@example.com

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
