spring.application.name=BachelorProject

# Server
server.port=8080

# PostgreSQL (values injected from Docker env)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection pool
spring.datasource.hikari.maximum-pool-size=5

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true


# SQL Init
spring.sql.init.mode=always

# Actuator
management.endpoints.web.exposure.include=health,info,mappings

# JWT config
app.jwt.issuer=${APP_JWT_ISSUER}
app.jwt.audience=${APP_JWT_AUDIENCE}
app.jwt.access-ttl-seconds=3600
app.jwt.secret=${APP_JWT_SECRET}

# Admin emails
app.auth.admin-emails=${APP_AUTH_ADMIN_EMAILS}
app.auth.allowed-emails=${APP_AUTH_ALLOWED_EMAILS:}